
export const GET_FISHES = "GET_FISHES";
export const CLEAR_FISHES = "CLEAR_FISHES";

export const GET_FISHES_DATA = "GET_FISHES_DATA";
export const CLEAR_FISHES_DATA = "CLEAR_FISHES_DATA";

export const GET_FISH_PROFILE = "GET_FISH_PROFILE";
export const CLEAR_FISH_PROFILE = "CLEAR_FISH_PROFILE";
export const EDIT_FISH_PROFILE_SUCCESS = "EDIT_FISH_PROFILE_SUCCESS";
export const EDIT_FISH_PROFILE_FAIL = "EDIT_FISH_PROFILE_FAIL";

export const GET_FISH_CATEGORIES = "GET_FISH_CATEGORIES";
export const ADD_FISH_CATEGORY = "ADD_FISH_CATEGORY";
export const CLEAR_FISH_CATEGORIES = "CLEAR_FISH_CATEGORIES";

export const FISH_REGISTER_SUCCESS = "FISH_REGISTER_SUCCESS";
export const FISH_REGISTER_FAIL = "FISH_REGISTER_FAIL";
export const DELETE_FISH = "DELETE_FISH";

export const SET_FISH_MODALS_HIDE = "SET_MODALS_HIDE";
export const SET_FISH_DELETE_SHOW = "SET_DELETE_SHOW";
export const SET_FISH_EDIT_SHOW = "SET_EDIT_SHOW";
export const SET_FISH_ADD_SHOW = "SET_ADD_SHOW";
export const SET_FISH_PROFILE_SHOW = "SET_FISH_PROFILE_SHOW";
export const SET_FISH_AMOUNT_SHOW = "SET_FISH_AMOUNT_SHOW";

export const ADD_FILTER = "ADD_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";