
export const FISHES_GET = "FISHES_GET";
export const FISHES_CLEAR = "FISHES_CLEAR";
export const FISHES_GET_DATA = "FISHES_GET_DATA";
export const FISHES_CLEAR_DATA = "FISHES_CLEAR_DATA";

export const FISHES_EDIT_PROFILE_SUCCESS = "FISHES_EDIT_PROFILE_SUCCESS";
export const FISHES_EDIT_PROFILE_FAIL = "FISHES_EDIT_PROFILE_FAIL";

export const FISHES_GET_CATEGORIES = "FISHES_GET_CATEGORIES";
export const FISHES_ADD_CATEGORY = "FISHES_ADD_CATEGORY";
export const FISHES_CLEAR_CATEGORIES = "FISHES_CLEAR_CATEGORIES";

export const FISHES_REGISTER_SUCCESS = "FISHES_REGISTER_SUCCESS";
export const FISHES_REGISTER_FAIL = "FISHES_REGISTER_FAIL";
export const FISHES_DELETE = "FISHES_DELETE";

export const FISHES_SET_MODALS_HIDE = "FISHES_SET_MODALS_HIDE";

export const FISHES_SET_DELETE_SHOW = "FISHES_SET_DELETE_SHOW";
export const FISHES_SET_EDIT_SHOW = "FISHES_SET_EDIT_SHOW";
export const FISHES_SET_ADD_SHOW = "FISHES_SET_ADD_SHOW";
export const FISHES_SET_PROFILE_SHOW = "FISHES_SET_PROFILE_SHOW";
export const FISHES_SET_AMOUNT_SHOW = "FISHES_SET_AMOUNT_SHOW";

export const FISHES_ADD_FILTER = "FISHES_ADD_FILTER";
export const FISHES_CLEAR_FILTER = "FISHES_CLEAR_FILTER";
export const FISHES_REMOVE_FILTER = "FISHES_REMOVE_FILTER";

export const FISHES_SHOW_ADD_CATEGORY = "FISHES_SHOW_ADD_CATEGORY";
