
export const CHANGE_FISH_AMOUNT = "CHANGE_FISH_AMOUNT";
export const REMOVE_ALL_FISH_FROM_TANK = "REMOVE_ALL_FISH_FROM_TANK";
export const REMOVE_FISH_FROM_TANK = "REMOVE_FISH_FROM_TANK";

export const GET_EQUIPMENT ="GET_EQUIPMENT";
export const FILL_EQUIPMENT = "FILL_EQUIPMENT";
export const CHANGE_EQUIPMENT = "CHANGE_EQUIPMENT";
export const REMOVE_ALL_EQUIPMENT = "REMOVE_ALL_EQUIPMENT";


export const CHANGE_PLANT_AMOUNT = "CHANGE_PLANT_AMOUNT";
export const REMOVE_ALL_PLANTS_FROM_TANK = "REMOVE_ALL_PLANTS_FROM_TANK";
export const REMOVE_PLANT_FROM_TANK = "REMOVE_PLANT_FROM_TANK";

export const FILL_TANK = "FILL_TANK";
export const CLEAR_TANK = "CLEAR_TANK";