
export interface plantCategory {
    id: number,
    name: string,
    slug: string
}

export interface plantData {
    "id": number,
    "name": string,
    "slug": string,
    "image": string|null,
    "approved": boolean,
    "created_at": string|null,
    "edited_at": string|null,
    "approved_at": string|null,
    "plant_value": number|null,
    "scientific_name": string|null,
    "family": string|null,
    "origin": string|null,
    "care": string|null,
    "ph_comfort_min": string|null,
    "ph_comfort_max": string|null,
    "ph_survive_min": string|null,
    "ph_survive_max": string|null,
    "water_hardness_comfort_min": string|null,
    "water_hardness_comfort_max": string|null,
    "water_hardness_survive_min": string|null,
    "water_hardness_survive_max": string|null,
    "temperature_comfort_min": string|null,
    "temperature_comfort_max": string|null,
    "temperature_survive_min": string|null,
    "temperature_survive_max": string|null,
    "aeration": number,
    "co2": number,
    "filtration": number,
    "illumination_intensity": number|null,
    "illumination_duration": string|null,
    "streams": number,
    "soil": string|null,
    "water_change": string|null,
    "description": string|null,
    "user_placeholder": number|null,
    "latest_editor": string|null,
    "approving_user": string|null,
    "category": number,
    "gallery": string[]|null[],
    "average_length": number
}



export interface fish {
    "id": number,
    "name": string,
    "slug": string|null,
    "image": string|null,
    "approved": boolean|null,
    "created_at": string|null,
    "edited_at": string|null,
    "approved_at": string|null,
    "scientific_name": string|null,
    "family": string|null,
    "origin": string|null,
    "social": string|null,
    "flock": string|null,
    "tank_level": string|null,
    "min_tank_size_one": string|null,
    "min_tank_size_pair": string|null,
    "min_tank_size_next_one": string|null,
    "min_water_volume_one": string|null,
    "min_water_volume_pair": string|null,
    "min_water_volume_next_one": string|null,
    "diet": string|null,
    "breeding": string|null,
    "care": string|null,
    "ph_comfort_min": string|null,
    "ph_comfort_max": string|null,
    "ph_survive_min": string|null,
    "ph_survive_max": string|null,
    "water_hardness_comfort_min": string|null,
    "water_hardness_comfort_max": string|null,
    "water_hardness_survive_min": string|null,
    "water_hardness_survive_max": string|null,
    "temperature_comfort_min": string|null,
    "temperature_comfort_max": string|null,
    "temperature_survive_min": string|null,
    "temperature_survive_max": string|null,
    "aeration": string|null,
    "filtration": string|null,
    "streams": string|null,
    "soil": string|null,
    "water_change": string|null,
    "lifespan": string|null,
    "male_average_length": string|null,
    "female_average_length": string|null,
    "fish_value": string|null,
    "description": string|null,
    "user_placeholder": number|null,
    "latest_editor": number|null,
    "approving_user": number|null,
    "category": number,
    "gallery": string[]|null[]
}