
export const PLANTS_GET = "PLANTS_GET";
export const PLANTS_CLEAR = "PLANTS_CLEAR";
export const PLANTS_GET_DATA = "PLANTS_GET_DATA"
export const PLANTS_CLEAR_DATA = "PLANTS_CLEAR_DATA"

export const PLANTS_EDIT_PROFILE_SUCCESS = "PLANTS_EDIT_PROFILE_SUCCESS";
export const PLANTS_EDIT_PROFILE_FAIL = "PLANTS_EDIT_PROFILE_FAIL";

export const PLANTS_GET_CATEGORIES = "PLANTS_GET_CATEGORIES";
export const PLANTS_ADD_CATEGORY = "PLANTS_ADD_CATEGORY";
export const PLANTS_CLEAR_CATEGORIES = "PLANTS_CLEAR_CATEGORIES";

export const PLANTS_REGISTER_SUCCESS = "PLANTS_REGISTER_SUCCESS";
export const PLANTS_REGISTER_FAIL = "PLANTS_REGISTER_FAIL";
export const PLANTS_DELETE = "PLANTS_DELETE";

export const PLANTS_SET_MODALS_HIDE = "PLANTS_SET_MODALS_HIDE";

export const PLANTS_SET_DELETE_SHOW = "PLANTS_SET_DELETE_SHOW";
export const PLANTS_SET_EDIT_SHOW = "PLANTS_SET_EDIT_SHOW";
export const PLANTS_SET_ADD_SHOW = "PLANTS_SET_ADD_SHOW";
export const PLANTS_SET_PROFILE_SHOW = "PLANTS_SET_PROFILE_SHOW";
export const PLANTS_SET_AMOUNT_SHOW = "PLANTS_SET_AMOUNT_SHOW";

export const PLANTS_ADD_FILTER = "PLANTS_ADD_FILTER";
export const PLANTS_CLEAR_FILTER = "PLANTS_CLEAR_FILTER";
export const PLANTS_REMOVE_FILTER = "PLANTS_REMOVE_FILTER";

export const PLANTS_SHOW_ADD_CATEGORY = "PLANTS_SHOW_ADD_CATEGORY";
