export const SET_LOGIN_SHOW = "SET_LOGIN_SHOW"
export const SET_LOGOUT_SHOW = "SET_LOGOUT_SHOW"
export const SET_LOGIN_HIDE = "SET_LOGIN_HIDE"
export const SET_LOGOUT_HIDE = "SET_LOGOUT_HIDE"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
