
export const SHOP_GET_ITEMS_DATA = "SHOP_GET_ITEMS_DATA";

export const SHOP_GET_ITEMS_SUCCESS = "SHOP_GET_ITEMS_SUCCESS";
export const SHOP_GET_ITEMS_FAIL = "SHOP_GET_ITEMS_FAIL";

export const SHOP_SET_MODALS_HIDE = "SHOP_SET_MODALS_HIDE";
export const SHOP_SET_SALE_DATA_SHOW = "SHOP_SET_SALE_DATA_SHOW";
export const SHOP_SET_SALE_EDITOR_SHOW = "SHOP_SET_SALE_EDITOR_SHOW";


export const SHOP_CHANGE_ITEM_IN_CART = "SHOP_CHANGE_ITEM_IN_CART";
export const SHOP_REMOVE_ITEM_FROM_CART = "SHOP_REMOVE_ITEM_FROM_CART";
export const SHOP_RESTORE_ITEM_IN_CART = "SHOP_RESTORE_ITEM_IN_CART";
export const SHOP_CLEAR_ITEMS_IN_CART = "SHOP_CLEAR_ITEMS_IN_CART";

export const SHOP_SHOW_CART = "SHOP_SHOW_CART";

export const SHOP_CREATE_ORDER_SUCCESS = "SHOP_CREATE_ORDER_SUCCESS";
export const SHOP_CREATE_ORDER_FAIL = "SHOP_CREATE_ORDER_FAIL";